version: "3.8"

services:
  db-clientes:
    image: postgres:16.2
    hostname: db-clientes
    container_name: "containerBancoDeDadosClientes"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    restart: always