version: "3.8"

services:
  db-cliente:
    image: postgres:16.2
    hostname: db-cliente
    container_name: "containerBancoDeDadosCliente"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'containerRabbitMQ'
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db-cliente
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  app-cliente:
    build:
      context: ./../
      dockerfile: Dockerfile
    container_name: app-sistema-cliente
    environment:
      POSTGRES_HOST: db-cliente:5432
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    restart: always
